title: Worldbuilding Network
description: >- # this means to ignore newlines until "baseurl:"
  The Worldbuilding Network, consiting of the r/Worldbuilding subreddit, Worldbuilding Discord
  server, and IRC, among others.
baseurl: "/worldbuilding-network" 

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - "*.psd"
  - "*.sh"
  - .gitignore

table_of_contents:
    dirs: [kaztron]

file-exists:
  # Nothing
